import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { writeFileSync, existsSync, unlinkSync, mkdirSync, rmSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { generateInitYaml, generateExpandedYaml } from "../src/cli.js";
import { loadFullConfig } from "../src/config.js";

const TMP = join(process.cwd(), ".test-cli-tmp");
const YAML_PATH = join(TMP, "swt3.yaml");

describe("swt3 init", () => {
  beforeEach(() => mkdirSync(TMP, { recursive: true }));
  afterEach(() => rmSync(TMP, { recursive: true, force: true }));

  it("generates valid YAML with correct profile", () => {
    const content = generateInitYaml("eu-ai-act-high-risk", "ACME_EU", "claims-agent");
    expect(content).toContain("profile: eu-ai-act-high-risk");
    expect(content).toContain("tenant_id: ACME_EU");
    expect(content).toContain("agent_id: claims-agent");
  });

  it("contains placeholder fields when values omitted", () => {
    const content = generateInitYaml("minimal", "", "");
    expect(content).toContain("tenant_id: YOUR_TENANT_ID");
    expect(content).toContain("api_key_env: SWT3_API_KEY");
    expect(content).toContain("agent_id: your-agent-name");
  });

  it("rejects invalid profile name", () => {
    // generateInitYaml itself doesn't validate -- the CLI handler does.
    // But the generated YAML with an invalid profile should fail loadFullConfig.
    const content = generateInitYaml("invalid-profile", "T", "A");
    writeFileSync(YAML_PATH, content, "utf-8");
    expect(() => loadFullConfig(YAML_PATH)).toThrow("Unknown profile");
  });

  it("generated file includes inline comments", () => {
    const content = generateInitYaml("nist-ai-rmf", "GOV_TENANT", "audit-bot");
    expect(content).toContain("# Generated by:");
    expect(content).toContain("# Optional overrides");
  });

  it("generated file is parseable by loadFullConfig", () => {
    process.env.SWT3_API_KEY = "axm_test_init";
    try {
      const content = generateInitYaml("minimal", "TEST_TENANT", "test-agent");
      writeFileSync(YAML_PATH, content, "utf-8");
      const loaded = loadFullConfig(YAML_PATH);
      expect(loaded.witnessOptions.tenantId).toBe("TEST_TENANT");
      expect(loaded.witnessOptions.agentId).toBe("test-agent");
      expect(loaded.configHash).toHaveLength(64);
    } finally {
      delete process.env.SWT3_API_KEY;
    }
  });

  it("--expand generates full profile template", () => {
    const content = generateExpandedYaml("eu-ai-act-high-risk", "ACME_EU", "claims-agent");
    expect(content).toContain("profile: eu-ai-act-high-risk");
    expect(content).toContain("tenant_id: ACME_EU");
    expect(content).toContain("--expand");
    expect(content).toContain("policy:");
    expect(content).toContain("trust_mesh:");
    expect(content).toContain("density_policy:");
  });

  it("--expand includes mcp_policy for cost-conscious", () => {
    const content = generateExpandedYaml("cost-conscious", "BUDGET_CO", "budget-bot");
    expect(content).toContain("mcp_policy:");
    expect(content).toContain("max_tokens_per_session:");
  });

  it("--expand throws for nonexistent profile", () => {
    expect(() => generateExpandedYaml("does-not-exist", "T", "A")).toThrow("Template not found");
  });

  it("--expand output is parseable by loadFullConfig", () => {
    process.env.SWT3_API_KEY = "axm_test_expand";
    try {
      const content = generateExpandedYaml("nist-ai-rmf", "GOV_EXPAND", "audit-bot");
      writeFileSync(YAML_PATH, content, "utf-8");
      const loaded = loadFullConfig(YAML_PATH);
      expect(loaded.witnessOptions.tenantId).toBe("GOV_EXPAND");
      expect(loaded.witnessOptions.agentId).toBe("audit-bot");
    } finally {
      delete process.env.SWT3_API_KEY;
    }
  });
});
