"""SWT3 CLI -- governance tooling for AI systems.

Commands:
    swt3 init              Interactive governance setup
    swt3 init --profile X  Non-interactive (CI/CD friendly)
    swt3 demo              Run the zero-friction demo
    swt3 doctor            Diagnose config health
    swt3 help              Show usage
"""

from __future__ import annotations

import sys
from pathlib import Path

VERSION = "0.5.1"

PROFILES = {
    "eu-ai-act-high-risk": "EU AI Act Article 6, Annex III (strict, signing required)",
    "granite-sovereign": "IBM Granite 4.1 + air-gap sovereign (strict, TPM required)",
    "mythos-defense": "Exploit chain containment (strict, rate limiting, tool blocklist)",
    "nist-ai-rmf": "NIST AI RMF + 800-53 GovCon (permissive, gradual adoption)",
    "owasp-agentic-top10": "OWASP Agentic AI Top 10 (runtime containment, fail closed)",
    "cost-conscious": "Agent token budget governance (cost attribution + audit trail)",
    "telecom-compliance": "Telecom AI governance (FCC + EU AI Act + fraud/network models)",
    "healthcare-clinical": "Clinical AI governance (HIPAA + FDA AI/ML + EU MDR)",
    "fintech-model-risk": "Model risk governance (SR 11-7 + GDPR + Basel III/IV)",
    "defense-govcon": "Defense/IC AI governance (CMMC + NIST 800-171 + FedRAMP)",
    "autonomous-systems": "Autonomous AI governance (EU Machinery Reg + EO 14110 + ISO 26262)",
    "insurance-underwriting": "Insurance AI governance (NAIC guidelines + state regs + GDPR)",
    "content-platform": "Content platform AI governance (DSA + Art. 50 + GPAI Code)",
    "microsoft-foundry": "Microsoft Foundry agent governance (AGT + OWASP Agentic + SOC 2)",
    "microsoft-agt": "Microsoft AGT policy engine governance (independent witness for AGT decisions)",
    "minimal": "Development / evaluation (no enforcement)",
}

PROFILE_NAMES = list(PROFILES.keys())


def _print_help() -> None:
    lines = [
        f"\nSWT3 CLI v{VERSION}\n",
        "Usage:",
        "  swt3 init                         Interactive governance setup",
        "  swt3 init --profile <name>        Non-interactive setup",
        "  swt3 init --profile <name> --expand   Full profile template",
        "  swt3 init --ci-template              Dump GitHub Action workflow",
        "  swt3 init --profile <name> --tenant <id> --agent <id>",
        "  swt3 status                       Compliance posture at a glance",
        "  swt3 status --full                All articles + all gaps",
        "  swt3 status --framework EU-AI-ACT Override target framework",
        "  swt3 status --json                Machine-readable (CI/CD)",
        "  swt3 status --compact             One-line summary",
        "  swt3 demo                         Run the zero-friction demo",
        "  swt3 doctor                       Diagnose config health",
        "  swt3 doctor --ci                   Strict mode (exit 1 on warnings)",
        "  swt3 procedures                   List all UCT procedures",
        "  swt3 procedures --namespace MDL   Filter by namespace",
        "  swt3 procedures --json            Machine-readable output",
        "  swt3 quickstart                   Generate a working example script",
        "  swt3 verify                       Offline anchor verification",
        "  swt3 audit                        Forensic chain timeline (html or json)",
        "  swt3 help                         Show this message\n",
        "Profiles:",
    ]
    for i, name in enumerate(PROFILE_NAMES):
        lines.append(f"  {i + 1}. {name:<24} {PROFILES[name]}")
    lines.append("\nDocs: https://sovereign.tenova.io/docs/\n")
    print("\n".join(lines))


def _resolve_template_path(profile: str) -> Path:
    return Path(__file__).parent / "templates" / f"{profile}.yaml"


def generate_expanded_yaml(profile: str, tenant_id: str, agent_id: str) -> str:
    template_path = _resolve_template_path(profile)
    if not template_path.is_file():
        raise FileNotFoundError(f"Template not found: {profile}")
    template = template_path.read_text(encoding="utf-8")
    header = "\n".join([
        f"# Generated by: swt3 init --profile {profile} --expand",
        "# Docs: https://sovereign.tenova.io/docs/",
        "",
        f"profile: {profile}",
        "",
        f"tenant_id: {tenant_id or 'YOUR_TENANT_ID'}",
        "api_key_env: SWT3_API_KEY",
        f"agent_id: {agent_id or 'your-agent-name'}",
        "",
    ])
    body = "\n".join(
        line for line in template.split("\n")
        if not line.startswith("# ") and not line.startswith("#!") and line.strip() != "#"
    ).lstrip("\n")
    return header + body


def generate_init_yaml(profile: str, tenant_id: str, agent_id: str) -> str:
    lines = [
        f"# Generated by: swt3 init --profile {profile}",
        "# Docs: https://sovereign.tenova.io/docs/",
        "",
        f"profile: {profile}",
        "",
        "# Required:",
        f"tenant_id: {tenant_id or 'YOUR_TENANT_ID'}",
        "api_key_env: SWT3_API_KEY",
        f"agent_id: {agent_id or 'your-agent-name'}",
        "",
        "# Optional overrides (uncomment to customize):",
        "# endpoint: https://sovereign.tenova.io",
        "# clearing_level: 2",
        "# jurisdiction: US",
        "# signing_key_env: SWT3_SIGNING_KEY",
        "",
    ]
    return "\n".join(lines)


def _get_flag(args: list, flag: str) -> str:
    try:
        idx = args.index(flag)
        return args[idx + 1]
    except (ValueError, IndexError):
        return ""


def _handle_ci_template() -> None:
    template_path = Path(__file__).parent / "templates" / "github-action.yml"
    if not template_path.is_file():
        print("GitHub Action template not found in package.", file=sys.stderr)
        sys.exit(1)
    print(template_path.read_text(encoding="utf-8"))


def handle_init(args: list) -> None:
    if "--ci-template" in args:
        _handle_ci_template()
        return

    output_path = Path.cwd() / "swt3.yaml"

    force = "--force" in args
    if output_path.exists() and not force:
        print("swt3.yaml already exists. Use --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    profile = _get_flag(args, "--profile")
    tenant_id = _get_flag(args, "--tenant")
    agent_id = _get_flag(args, "--agent")

    if profile and profile not in PROFILE_NAMES:
        print(f"Unknown profile: '{profile}'", file=sys.stderr)
        print(f"Valid profiles: {', '.join(PROFILE_NAMES)}", file=sys.stderr)
        sys.exit(1)

    if not profile:
        print("\n  SWT3 Governance Setup\n")
        print("  Choose a compliance profile:")
        for i, name in enumerate(PROFILE_NAMES):
            print(f"    {i + 1}. {name:<24} {PROFILES[name]}")

        try:
            choice = input(f"\n  Profile [1-{len(PROFILE_NAMES)}]: ")
            idx = int(choice) - 1
            if idx < 0 or idx >= len(PROFILE_NAMES):
                raise ValueError
            profile = PROFILE_NAMES[idx]
        except (ValueError, EOFError):
            print("  Invalid selection.", file=sys.stderr)
            sys.exit(1)

        if not tenant_id:
            tenant_id = input("  Tenant ID: ")
        if not agent_id:
            agent_id = input("  Agent ID [optional]: ")

    expand = "--expand" in args
    content = (
        generate_expanded_yaml(profile, tenant_id, agent_id)
        if expand
        else generate_init_yaml(profile, tenant_id, agent_id)
    )
    output_path.write_text(content, encoding="utf-8")

    suffix = " (expanded profile)" if expand else ""
    print(f"\n  Created: swt3.yaml{suffix}\n")
    print("  Next: set SWT3_API_KEY in your environment, then:")
    print("    from swt3_ai import Witness")
    print("    witness = Witness.from_config()  # done.\n")


_QUICKSTART_PY = '''\
"""SWT3 AI Witness quickstart -- generated by `swt3 quickstart`."""

from swt3_ai import Witness

# Create a witness (reads .swt3.yaml if present, or uses defaults)
witness = Witness(
    tenant_id="QUICKSTART_TENANT",
    clearing_level=1,
)

# Wrap an inference call -- the SDK hashes inputs/outputs and mints anchors
response = witness.wrap(
    prompt="What are the three laws of robotics?",
    response="1. A robot may not injure a human being...",
    model_id="quickstart-model",
    provider="local",
)

print(f"Response: {response.response[:60]}...")
print(f"Anchors minted: {len(witness.pending)}")

# Flush anchors (prints to console in local mode)
results = witness.flush()
for r in results:
    print(f"  {r.procedure_id}: {r.anchor_fingerprint}")

print("\\nDone. See https://sovereign.tenova.io/docs/ for full documentation.")
'''


def _handle_quickstart() -> None:
    """Generate a quickstart example script in the current directory."""
    out = Path("swt3_quickstart.py")
    if out.exists():
        print(f"  {out} already exists. Remove it first.", file=sys.stderr)
        sys.exit(1)
    out.write_text(_QUICKSTART_PY, encoding="utf-8")
    print(f"\n  Created: {out}")
    print("  Run it:  python swt3_quickstart.py\n")


def main() -> None:
    args = sys.argv[1:]
    cmd = args[0] if args else None

    if cmd == "status":
        from .status import handle_status
        handle_status(args[1:])
    elif cmd == "init":
        handle_init(args[1:])
    elif cmd == "demo":
        if "--mesh-test" in args[1:]:
            from .demo import run_mesh_test
            run_mesh_test()
        else:
            from .demo import main as demo_main
            demo_main()
    elif cmd == "doctor":
        if "--friction-test" in args[1:]:
            from .doctor import run_friction_test, print_friction_results
            steps = run_friction_test()
            print_friction_results(steps)
            if any(s.status == "fail" for s in steps):
                sys.exit(1)
        else:
            from .doctor import run_doctor_checks, print_doctor_results
            checks = run_doctor_checks()
            use_json = "--json" in args[1:]
            ci_mode = "--ci" in args[1:] or "--strict" in args[1:]
            print_doctor_results(checks, use_json=use_json, ci_mode=ci_mode)
            has_fail = any(c.status == "fail" for c in checks)
            has_warn = any(c.status == "warn" for c in checks)
            if has_fail or (ci_mode and has_warn):
                sys.exit(1)
    elif cmd == "audit":
        from .exporters.chain_monitor import ChainMonitorExporter
        fmt = _get_flag(args[1:], "--format") or "html"
        wal_dir = _get_flag(args[1:], "--wal-path")
        tenant_id, agent_id, clearing_level = "UNKNOWN", "UNKNOWN", 1
        try:
            from .config import load_full_config
            loaded = load_full_config()
            tenant_id = loaded.witness_kwargs.get("tenant_id", tenant_id)
            agent_id = loaded.witness_kwargs.get("agent_id", agent_id)
            clearing_level = loaded.witness_kwargs.get("clearing_level", clearing_level)
        except Exception:
            pass
        kw = {"tenant_id": tenant_id, "agent_id": agent_id, "clearing_level": clearing_level}
        if wal_dir:
            kw["wal_dir"] = wal_dir
        exporter = ChainMonitorExporter(**kw)
        if fmt == "json":
            print(exporter.export_json())
        else:
            html_out = exporter.export_html()
            out_path = "swt3-audit-report.html"
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(html_out)
            print(f"Audit report saved: {out_path}")
    elif cmd == "verify":
        sub = args[1:]
        anchor = _get_flag(sub, "--anchor")
        tenant = _get_flag(sub, "--tenant")
        procedure = _get_flag(sub, "--procedure")
        fa = _get_flag(sub, "--fa")
        fb = _get_flag(sub, "--fb")
        fc = _get_flag(sub, "--fc")
        ts = _get_flag(sub, "--ts")

        if not all([anchor, tenant, procedure, fa, fb, fc, ts]):
            print(
                "\nUsage:\n"
                "  swt3 verify --anchor <token> --tenant <id> --procedure <id> "
                "--fa <n> --fb <n> --fc <n> --ts <ms>\n\n"
                "Example:\n"
                "  swt3 verify --anchor SWT3-E-AWS-AI-AIINF1-PASS-1773316622-a1b2c3d4e5f6 \\\n"
                "    --tenant MY_TENANT --procedure AI-INF.1 --fa 1 --fb 1 --fc 0 --ts 1773316622000\n\n"
                "Zero network calls. Recomputes the SHA-256 fingerprint locally."
            )
        else:
            from .fingerprint import mint_fingerprint

            recomputed = mint_fingerprint(
                tenant, procedure,
                float(fa), float(fb), float(fc),
                int(ts),
            )
            claimed = anchor.rsplit("-", 1)[-1] if anchor else ""
            match = recomputed == claimed

            if match:
                print(f"\033[32mCERTIFIED TRUTH\033[0m")
                print(f"  Fingerprint: {recomputed}")
            else:
                print(f"\033[31mTAMPERED\033[0m")
                print(f"  Claimed:    {claimed}")
                print(f"  Recomputed: {recomputed}")
    elif cmd == "procedures":
        from .procedures import handle_procedures
        namespace = _get_flag(args[1:], "--namespace")
        use_json = "--json" in args[1:]
        handle_procedures(namespace=namespace, use_json=use_json)
    elif cmd == "quickstart":
        _handle_quickstart()
    elif cmd in ("help", "--help", "-h", None):
        _print_help()
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        _print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
