"""SWT3 CLI -- governance tooling for AI systems.

Commands:
    swt3 init              Interactive governance setup
    swt3 init --profile X  Non-interactive (CI/CD friendly)
    swt3 demo              Run the zero-friction demo
    swt3 doctor            Diagnose config health
    swt3 help              Show usage
"""

from __future__ import annotations

import sys
from pathlib import Path

VERSION = "0.5.1"

PROFILES = {
    "eu-ai-act-high-risk": "EU AI Act Article 6, Annex III (strict, signing required)",
    "granite-sovereign": "IBM Granite 4.1 + air-gap sovereign (strict, TPM required)",
    "mythos-defense": "Exploit chain containment (strict, rate limiting, tool blocklist)",
    "nist-ai-rmf": "NIST AI RMF + 800-53 GovCon (permissive, gradual adoption)",
    "owasp-agentic-top10": "OWASP Agentic AI Top 10 (runtime containment, fail closed)",
    "minimal": "Development / evaluation (no enforcement)",
}

PROFILE_NAMES = list(PROFILES.keys())


def _print_help() -> None:
    lines = [
        f"\nSWT3 CLI v{VERSION}\n",
        "Usage:",
        "  swt3 init                         Interactive governance setup",
        "  swt3 init --profile <name>        Non-interactive setup",
        "  swt3 init --profile <name> --tenant <id> --agent <id>",
        "  swt3 demo                         Run the zero-friction demo",
        "  swt3 doctor                       Diagnose config health",
        "  swt3 audit                        Forensic chain timeline (html or json)",
        "  swt3 help                         Show this message\n",
        "Profiles:",
    ]
    for i, name in enumerate(PROFILE_NAMES):
        lines.append(f"  {i + 1}. {name:<24} {PROFILES[name]}")
    lines.append("\nDocs: https://sovereign.tenova.io/docs/\n")
    print("\n".join(lines))


def generate_init_yaml(profile: str, tenant_id: str, agent_id: str) -> str:
    lines = [
        f"# Generated by: swt3 init --profile {profile}",
        "# Docs: https://sovereign.tenova.io/docs/",
        "",
        f"profile: {profile}",
        "",
        "# Required:",
        f"tenant_id: {tenant_id or 'YOUR_TENANT_ID'}",
        "api_key_env: SWT3_API_KEY",
        f"agent_id: {agent_id or 'your-agent-name'}",
        "",
        "# Optional overrides (uncomment to customize):",
        "# endpoint: https://sovereign.tenova.io",
        "# clearing_level: 2",
        "# jurisdiction: US",
        "# signing_key_env: SWT3_SIGNING_KEY",
        "",
    ]
    return "\n".join(lines)


def _get_flag(args: list, flag: str) -> str:
    try:
        idx = args.index(flag)
        return args[idx + 1]
    except (ValueError, IndexError):
        return ""


def handle_init(args: list) -> None:
    output_path = Path.cwd() / "swt3.yaml"

    force = "--force" in args
    if output_path.exists() and not force:
        print("swt3.yaml already exists. Use --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    profile = _get_flag(args, "--profile")
    tenant_id = _get_flag(args, "--tenant")
    agent_id = _get_flag(args, "--agent")

    if profile and profile not in PROFILE_NAMES:
        print(f"Unknown profile: '{profile}'", file=sys.stderr)
        print(f"Valid profiles: {', '.join(PROFILE_NAMES)}", file=sys.stderr)
        sys.exit(1)

    if not profile:
        print("\n  SWT3 Governance Setup\n")
        print("  Choose a compliance profile:")
        for i, name in enumerate(PROFILE_NAMES):
            print(f"    {i + 1}. {name:<24} {PROFILES[name]}")

        try:
            choice = input(f"\n  Profile [1-{len(PROFILE_NAMES)}]: ")
            idx = int(choice) - 1
            if idx < 0 or idx >= len(PROFILE_NAMES):
                raise ValueError
            profile = PROFILE_NAMES[idx]
        except (ValueError, EOFError):
            print("  Invalid selection.", file=sys.stderr)
            sys.exit(1)

        if not tenant_id:
            tenant_id = input("  Tenant ID: ")
        if not agent_id:
            agent_id = input("  Agent ID [optional]: ")

    content = generate_init_yaml(profile, tenant_id, agent_id)
    output_path.write_text(content, encoding="utf-8")

    print("\n  Created: swt3.yaml\n")
    print("  Next: set SWT3_API_KEY in your environment, then:")
    print("    from swt3_ai import Witness")
    print("    witness = Witness.from_config()  # done.\n")


def main() -> None:
    args = sys.argv[1:]
    cmd = args[0] if args else None

    if cmd == "init":
        handle_init(args[1:])
    elif cmd == "demo":
        if "--mesh-test" in args[1:]:
            from .demo import run_mesh_test
            run_mesh_test()
        else:
            from .demo import main as demo_main
            demo_main()
    elif cmd == "doctor":
        if "--friction-test" in args[1:]:
            from .doctor import run_friction_test, print_friction_results
            steps = run_friction_test()
            print_friction_results(steps)
            if any(s.status == "fail" for s in steps):
                sys.exit(1)
        else:
            from .doctor import run_doctor_checks, print_doctor_results
            checks = run_doctor_checks()
            use_json = "--json" in args[1:]
            print_doctor_results(checks, use_json=use_json)
            has_fail = any(c.status == "fail" for c in checks)
            if has_fail:
                sys.exit(1)
    elif cmd == "audit":
        from .exporters.chain_monitor import ChainMonitorExporter
        fmt = _get_flag(args[1:], "--format") or "html"
        wal_dir = _get_flag(args[1:], "--wal-path")
        tenant_id, agent_id, clearing_level = "UNKNOWN", "UNKNOWN", 1
        try:
            from .config import load_full_config
            loaded = load_full_config()
            tenant_id = loaded.witness_kwargs.get("tenant_id", tenant_id)
            agent_id = loaded.witness_kwargs.get("agent_id", agent_id)
            clearing_level = loaded.witness_kwargs.get("clearing_level", clearing_level)
        except Exception:
            pass
        kw = {"tenant_id": tenant_id, "agent_id": agent_id, "clearing_level": clearing_level}
        if wal_dir:
            kw["wal_dir"] = wal_dir
        exporter = ChainMonitorExporter(**kw)
        if fmt == "json":
            print(exporter.export_json())
        else:
            html_out = exporter.export_html()
            out_path = "swt3-audit-report.html"
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(html_out)
            print(f"Audit report saved: {out_path}")
    elif cmd in ("help", "--help", "-h", None):
        _print_help()
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        _print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
