#!/usr/bin/env node
/**
 * SWT3 CLI -- governance tooling for AI systems.
 *
 * Commands:
 *   swt3 init              Interactive governance setup
 *   swt3 init --profile X  Non-interactive (CI/CD friendly)
 *   swt3 demo              Run the zero-friction demo
 *   swt3 doctor            Diagnose config health
 *   swt3 help              Show usage
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline";

const VERSION = "0.5.1";

const PROFILES: Record<string, string> = {
  "eu-ai-act-high-risk": "EU AI Act Article 6, Annex III (strict, signing required)",
  "granite-sovereign": "IBM Granite 4.1 + air-gap sovereign (strict, TPM required)",
  "mythos-defense": "Exploit chain containment (strict, rate limiting, tool blocklist)",
  "nist-ai-rmf": "NIST AI RMF + 800-53 GovCon (permissive, gradual adoption)",
  "owasp-agentic-top10": "OWASP Agentic AI Top 10 (runtime containment, fail closed)",
  "cost-conscious": "Agent token budget governance (cost attribution + audit trail)",
  "telecom-compliance": "Telecom AI governance (FCC + EU AI Act + fraud/network models)",
  "healthcare-clinical": "Clinical AI governance (HIPAA + FDA AI/ML + EU MDR)",
  "fintech-model-risk": "Model risk governance (SR 11-7 + GDPR + Basel III/IV)",
  "defense-govcon": "Defense/IC AI governance (CMMC + NIST 800-171 + FedRAMP)",
  "autonomous-systems": "Autonomous AI governance (EU Machinery Reg + EO 14110 + ISO 26262)",
  "insurance-underwriting": "Insurance AI governance (NAIC guidelines + state regs + GDPR)",
  "content-platform": "Content platform AI governance (DSA + Art. 50 + GPAI Code)",
  "microsoft-foundry": "Microsoft Foundry agent governance (AGT + OWASP Agentic + SOC 2)",
  "microsoft-agt": "Microsoft AGT policy engine governance (independent witness for AGT decisions)",
  "minimal": "Development / evaluation (no enforcement)",
};

const PROFILE_NAMES = Object.keys(PROFILES);

function printHelp(): void {
  console.log(`
SWT3 CLI v${VERSION}

Usage:
  swt3 init                         Interactive governance setup
  swt3 init --profile <name>        Non-interactive setup
  swt3 init --profile <name> --expand   Full profile template
  swt3 init --ci-template              Dump GitHub Action workflow
  swt3 init --profile <name> --tenant <id> --agent <id>
  swt3 demo                         Run the zero-friction demo
  swt3 doctor                       Diagnose config health
  swt3 doctor --ci                   Strict mode (exit 1 on warnings)
  swt3 verify                       Offline anchor verification
  swt3 audit                        Forensic chain timeline (html or json)
  swt3 help                         Show this message

Profiles:
${PROFILE_NAMES.map((n, i) => `  ${i + 1}. ${n.padEnd(24)} ${PROFILES[n]}`).join("\n")}

Docs: https://sovereign.tenova.io/docs/
`);
}

function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, resolve));
}

function resolveTemplatePath(profile: string): string {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  return join(__dirname, "..", "templates", `${profile}.yaml`);
}

export function generateExpandedYaml(profile: string, tenantId: string, agentId: string): string {
  const templatePath = resolveTemplatePath(profile);
  if (!existsSync(templatePath)) {
    throw new Error(`Template not found: ${profile}`);
  }
  const template = readFileSync(templatePath, "utf-8");
  const header = [
    `# Generated by: swt3 init --profile ${profile} --expand`,
    `# Docs: https://sovereign.tenova.io/docs/`,
    ``,
    `profile: ${profile}`,
    ``,
    `tenant_id: ${tenantId || "YOUR_TENANT_ID"}`,
    `api_key_env: SWT3_API_KEY`,
    `agent_id: ${agentId || "your-agent-name"}`,
    ``,
  ].join("\n");
  // Strip the template's own header comments and any profile/clearing_level already in header
  const body = template
    .split("\n")
    .filter((line) => !line.startsWith("# ") && !line.startsWith("#!") && line.trim() !== "#")
    .join("\n")
    .replace(/^\n+/, "");
  return header + body;
}

export function generateInitYaml(profile: string, tenantId: string, agentId: string): string {
  const lines = [
    `# Generated by: swt3 init --profile ${profile}`,
    `# Docs: https://sovereign.tenova.io/docs/`,
    ``,
    `profile: ${profile}`,
    ``,
    `# Required:`,
    `tenant_id: ${tenantId || "YOUR_TENANT_ID"}`,
    `api_key_env: SWT3_API_KEY`,
    `agent_id: ${agentId || "your-agent-name"}`,
    ``,
    `# Optional overrides (uncomment to customize):`,
    `# endpoint: https://sovereign.tenova.io`,
    `# clearing_level: 2`,
    `# jurisdiction: US`,
    `# signing_key_env: SWT3_SIGNING_KEY`,
    ``,
  ];
  return lines.join("\n");
}

function handleCiTemplate(): void {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const templatePath = join(__dirname, "..", "templates", "github-action.yml");
  if (!existsSync(templatePath)) {
    console.error("GitHub Action template not found in package.");
    process.exit(1);
  }
  console.log(readFileSync(templatePath, "utf-8"));
}

async function handleInit(args: string[]): Promise<void> {
  if (args.includes("--ci-template")) {
    handleCiTemplate();
    return;
  }

  const outputPath = join(process.cwd(), "swt3.yaml");

  // Check overwrite protection
  const forceIdx = args.indexOf("--force");
  const force = forceIdx !== -1;
  if (existsSync(outputPath) && !force) {
    console.error("swt3.yaml already exists. Use --force to overwrite.");
    process.exit(1);
  }

  // Parse flags
  const profileIdx = args.indexOf("--profile");
  const tenantIdx = args.indexOf("--tenant");
  const agentIdx = args.indexOf("--agent");

  let profile = profileIdx !== -1 ? args[profileIdx + 1] : "";
  let tenantId = tenantIdx !== -1 ? args[tenantIdx + 1] : "";
  let agentId = agentIdx !== -1 ? args[agentIdx + 1] : "";

  // Validate profile if provided
  if (profile && !PROFILE_NAMES.includes(profile)) {
    console.error(`Unknown profile: '${profile}'`);
    console.error(`Valid profiles: ${PROFILE_NAMES.join(", ")}`);
    process.exit(1);
  }

  // Interactive mode if no profile specified
  if (!profile) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });

    console.log(`\n  SWT3 Governance Setup\n`);
    console.log(`  Choose a compliance profile:`);
    PROFILE_NAMES.forEach((name, i) => {
      console.log(`    ${i + 1}. ${name.padEnd(24)} ${PROFILES[name]}`);
    });

    const choice = await ask(rl, `\n  Profile [1-${PROFILE_NAMES.length}]: `);
    const idx = parseInt(choice, 10) - 1;
    if (isNaN(idx) || idx < 0 || idx >= PROFILE_NAMES.length) {
      console.error("  Invalid selection.");
      rl.close();
      process.exit(1);
    }
    profile = PROFILE_NAMES[idx];

    if (!tenantId) {
      tenantId = await ask(rl, "  Tenant ID: ");
    }
    if (!agentId) {
      agentId = await ask(rl, "  Agent ID [optional]: ");
    }

    rl.close();
  }

  const expand = rest.includes("--expand");
  const content = expand
    ? generateExpandedYaml(profile, tenantId, agentId)
    : generateInitYaml(profile, tenantId, agentId);
  writeFileSync(outputPath, content, "utf-8");

  console.log(`\n  Created: swt3.yaml${expand ? " (expanded profile)" : ""}\n`);
  console.log(`  Next: set SWT3_API_KEY in your environment, then:`);
  console.log(`    import { Witness } from "@tenova/swt3-ai";`);
  console.log(`    const witness = Witness.fromConfig();  // done.\n`);
}

async function main(): Promise<void> {
  const [, , cmd, ...rest] = process.argv;

  switch (cmd) {
    case "init":
      await handleInit(rest);
      break;
    case "demo": {
      if (rest.includes("--mesh-test")) {
        const { runMeshTest } = await import("./demo.js");
        await runMeshTest();
      } else {
        const demo = await import("./demo.js");
        demo.main();
      }
      break;
    }
    case "doctor": {
      if (rest.includes("--friction-test")) {
        const { runFrictionTest, printFrictionResults } = await import("./doctor.js");
        const steps = await runFrictionTest();
        printFrictionResults(steps);
        if (steps.some((s) => s.status === "fail")) process.exit(1);
      } else {
        const { runDoctorChecks, printDoctorResults } = await import("./doctor.js");
        const checks = runDoctorChecks();
        const jsonFlag = rest.includes("--json");
        const ciFlag = rest.includes("--ci") || rest.includes("--strict");
        printDoctorResults(checks, jsonFlag, ciFlag);
        const hasFail = checks.some((c) => c.status === "fail");
        const hasWarn = checks.some((c) => c.status === "warn");
        if (hasFail || (ciFlag && hasWarn)) process.exit(1);
      }
      break;
    }
    case "audit": {
      const { ChainMonitorExporter } = await import("./exporters/chain-monitor.js");
      const fmtIdx = rest.indexOf("--format");
      const format = fmtIdx !== -1 && rest[fmtIdx + 1] ? rest[fmtIdx + 1] : "html";
      const walIdx = rest.indexOf("--wal-path");
      const walDir = walIdx !== -1 && rest[walIdx + 1] ? rest[walIdx + 1] : undefined;
      let tenantId = "UNKNOWN", agentId = "UNKNOWN", clearingLevel = 1;
      try {
        const { loadFullConfig } = await import("./config.js");
        const cfg = loadFullConfig();
        const opts = cfg.witnessOptions as Record<string, unknown>;
        tenantId = (opts.tenantId as string) ?? tenantId;
        agentId = (opts.agentId as string) ?? agentId;
        clearingLevel = (opts.clearingLevel as number) ?? clearingLevel;
      } catch { /* no config */ }
      const exporter = new ChainMonitorExporter({ walDir, tenantId, agentId, clearingLevel });
      if (format === "json") {
        console.log(exporter.exportJson());
      } else {
        const { writeFileSync } = await import("node:fs");
        const html = exporter.exportHtml();
        const outPath = "swt3-audit-report.html";
        writeFileSync(outPath, html, "utf-8");
        console.log(`Audit report saved: ${outPath}`);
      }
      break;
    }
    case "verify": {
      const flagVal = (flag: string): string | undefined => {
        const idx = rest.indexOf(flag);
        return idx !== -1 && rest[idx + 1] ? rest[idx + 1] : undefined;
      };
      const anchor = flagVal("--anchor");
      const tenant = flagVal("--tenant");
      const procedure = flagVal("--procedure");
      const fa = flagVal("--fa");
      const fb = flagVal("--fb");
      const fc = flagVal("--fc");
      const ts = flagVal("--ts");

      if (!anchor || !tenant || !procedure || !fa || !fb || !fc || !ts) {
        console.log(`
Usage:
  swt3 verify --anchor <token> --tenant <id> --procedure <id> --fa <n> --fb <n> --fc <n> --ts <ms>

Example:
  swt3 verify --anchor SWT3-E-AWS-AI-AIINF1-PASS-1773316622-a1b2c3d4e5f6 \\
    --tenant MY_TENANT --procedure AI-INF.1 --fa 1 --fb 1 --fc 0 --ts 1773316622000

Zero network calls. Recomputes the SHA-256 fingerprint locally.`);
        break;
      }

      const { mintFingerprint } = await import("./fingerprint.js");
      const recomputed = mintFingerprint(
        tenant, procedure,
        parseFloat(fa), parseFloat(fb), parseFloat(fc),
        parseInt(ts, 10),
      );
      const claimed = anchor.split("-").pop() ?? "";
      const match = recomputed === claimed;

      if (match) {
        console.log(`\x1b[32mCERTIFIED TRUTH\x1b[0m`);
        console.log(`  Fingerprint: ${recomputed}`);
      } else {
        console.log(`\x1b[31mTAMPERED\x1b[0m`);
        console.log(`  Claimed:    ${claimed}`);
        console.log(`  Recomputed: ${recomputed}`);
      }
      break;
    }
    case "help":
    case "--help":
    case "-h":
    case undefined:
      printHelp();
      break;
    default:
      console.error(`Unknown command: ${cmd}`);
      printHelp();
      process.exit(1);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
