{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "swt3-witness.serviceAccountName" . }}
  labels:
    {{- include "swt3-witness.labels" . | nindent 4 }}
{{- end }}
